language: python

cache:
  pip: true

matrix:
  include:
    - python: "3.5"
      env: TOX_ENV=py35,py35-dramatiq-1.3,py-dramatiq-1.4,py35-dramatiq-dev

    - python: "3.6"
      env: TOX_ENV=py36,py36-dramatiq-1.3,py-dramatiq-1.4,py36-dramatiq-dev

    - python: "3.7"
      dist: xenial
      env: TOX_ENV=py37,py37-dramatiq-1.3,py-dramatiq-1.4,py37-dramatiq-dev

    - python: "3.8"
      dist: xenial
      env: TOX_ENV=py38,py38-dramatiq-1.3,py-dramatiq-1.4,py38-dramatiq-dev

    - python: "3.9"
      dist: xenial
      env: TOX_ENV=py39,py39-dramatiq-dev

    - name: Linting
      python: "3.9"
      env: TOX_ENV=lint

install:
    - pip install tox

script: tox -e $TOX_ENV

after_success:
  # Submit data from .coverage to coveralls on success
  - pip install coveralls
  - coveralls
